[build]
builder = "dockerfile"

[deploy]
startCommand = "npx prisma migrate deploy && npm start"
healthcheckPath = "/api/users"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
